St feature survey screen
redacademy/monkiri-spring-2019 pull request #37
Opened 2019-06-12 18:08 UTC by saveentoor

Added content to the page and styled it.

2019-06-12 19:10 UTC, teelau requested changes
Connect this with an issue

2019-06-12 20:10 UTC, siddharthparmar7 requested changes
Please make the changes.

2019-06-12 20:10 UTC, siddharthparmar7 commented on client/App.js
> +    // return <RootStackNavigator />;
Use the RootStackNavigator and do not push code with comments.

2019-06-12 20:10 UTC, siddharthparmar7 commented on client/js/screens/Lessons/SurveyDifficulty/SurveyDifficultyContainer.js
> +      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
move styles to styles.js file.

2019-06-12 20:10 UTC, siddharthparmar7 commented on client/js/screens/Lessons/SurveyDifficulty/SurveyDifficultyContainer.js
> +
Please use your styles.js and move all your styles from here to styles.js file.

2019-06-13 16:26 UTC, siddharthparmar7 requested changes
Please resolve merge conflicts. Thank you.

2019-06-13 16:26 UTC, siddharthparmar7 commented on client/js/screens/Lessons/SurveyDifficulty/styles.js
> +    height: 150
Please use dynamic height and width for all your images and container so that they can look the same on different phones.

2019-06-13 16:26 UTC, siddharthparmar7 commented on client/js/screens/Lessons/SurveyDifficulty/styles.js
> +    height: 220,
use flex instead of width and height

2019-06-13 16:26 UTC, siddharthparmar7 commented on client/js/screens/Lessons/SurveyDifficulty/styles.js
> +    width: 130,
use flex instead of width and height

2019-06-13 16:26 UTC, siddharthparmar7 commented on client/js/screens/Lessons/SurveyDifficulty/styles.js
> +    height: 220,
use flex instead of width and height

2019-06-13 16:26 UTC, siddharthparmar7 commented on client/js/screens/Lessons/SurveyDifficulty/styles.js
> +    paddingBottom: 40,
use flexbox properties instead of applying huge padding.

2019-06-13 16:26 UTC, teelau requested changes
Fix merge conflicts

2019-06-14 16:40 UTC, siddharthparmar7 requested changes
Please make the changes and we can merge this feature into develop branch. Thank you.

2019-06-14 16:40 UTC, siddharthparmar7 commented on client/App.js
> +    return <SurveyDifficultyContainer />;
Please use RootStackNavigator. Thank you.

2019-06-14 16:40 UTC, siddharthparmar7 commented on client/js/screens/Lessons/SurveyDifficulty/SurveyDifficultyContainer.js
> +        {/* </View> */}
remove commented code.

2019-06-14 16:40 UTC, siddharthparmar7 commented on client/js/screens/Lessons/SurveyDifficulty/SurveyDifficultyContainer.js
> +    title: "LESSONS"
Is there a title? Lessons?

2019-06-14 16:40 UTC, siddharthparmar7 commented on client/js/screens/Lessons/SurveyDifficulty/styles.js
> +    // backgroundColor: theme.colors.monikOrange,
remove commented code. Thank you.

2019-06-14 16:40 UTC, siddharthparmar7 commented on client/App.js
> +import SurveyDifficultyContainer from "./js/screens/Lessons/SurveyDifficulty/SurveyDifficultyContainer";
remove unnecessary imports. Thank you.

2019-06-17 21:37 UTC, teelau approved these changes

2019-06-18 18:11 UTC, siddharthparmar7 approved these changes

2019-06-18 18:11 UTC, merged