Nz feature reusable components
redacademy/monkiri-spring-2019 pull request #53
Opened 2019-06-13 18:38 UTC by naijizhang

### Add reusable components
- TopicList Component
- TopicItem Component
- Add touchable feature on TopicItem

2019-06-13 20:20 UTC, siddharthparmar7 requested changes
Please make the changes. Thank you.

2019-06-13 20:20 UTC, siddharthparmar7 commented on client/js/components/TopicItem/TopicItem.js
> +
move all your styles to styles.js file.

2019-06-13 22:18 UTC, teelau approved these changes

2019-06-14 16:37 UTC, siddharthparmar7 approved these changes

2019-06-14 16:37 UTC, merged