St feature lesson screen
redacademy/monkiri-spring-2019 pull request #62
Opened 2019-06-15 19:41 UTC by saveentoor

Edit and finished styling for one component in Lessons (My lessons)

2019-06-17 16:05 UTC, siddharthparmar7 requested changes
Is this a duplicate pull request? Please resolve merge conflicts on this branch. Thank you.

2019-06-17 17:27 UTC, teelau commented
Rebase this branch after the changes for the SurveyDifficulty are merged, this branch contains changes from that feature and the new lessons screen feature.

2019-06-17 17:27 UTC, teelau commented
Connect with an issue

2019-06-18 18:12 UTC, siddharthparmar7 commented
Please resolve merge conflicts for this branch and provide valid labels and milestone.

2019-06-18 20:09 UTC, teelau requested changes

2019-06-18 20:09 UTC, teelau commented on client/js/screens/Lessons/LessonsContainer.js
> +        </View>
Remove this testing stuff

2019-06-18 20:22 UTC, siddharthparmar7 requested changes
Please make the changes. Thank you.

2019-06-18 20:22 UTC, siddharthparmar7 commented on client/js/screens/Lessons/LessonsContainer.js
> +          <View style={[{ backgroundColor: "#99c355" }, styles.iconContainer]}>
move this background color to the styles.js file

2019-06-18 20:22 UTC, siddharthparmar7 commented on client/js/screens/Lessons/LessonsContainer.js
> +        </View>
Please move all your styles to styles.js.

2019-06-19 22:14 UTC, siddharthparmar7 commented
Please resolve merge conflicts.

2019-06-20 16:56 UTC, siddharthparmar7 approved these changes

2019-06-20 16:56 UTC, merged