Ek feature profile screen
redacademy/monkiri-spring-2019 pull request #81
Opened 2019-06-19 22:36 UTC by ekaynak94

UI for profile screen

2019-06-19 23:40 UTC, siddharthparmar7 requested changes
Please make the changes. Thank you.

2019-06-19 23:40 UTC, siddharthparmar7 commented on client/js/screens/Profile/Profile.js
> +              logOut();
`await logOut()`

2019-06-20 17:27 UTC, teelau commented on client/js/screens/Profile/Profile.js
> +          <Text style={styles.userStatsLessons}>0</Text>
Will this value be pulled from your database to check how many lessons a certain logged in user has completed?

2019-06-20 23:30 UTC, siddharthparmar7 approved these changes

2019-06-20 23:30 UTC, merged