St feature stage one
redacademy/monkiri-spring-2019 pull request #89
Opened 2019-06-20 23:45 UTC by saveentoor

2019-06-21 16:16 UTC, teelau commented
Somethings not right, some of these older commits are already merged and not part of this feature. Can you cherry pick only the latest changes for this feature?

2019-06-21 16:17 UTC, siddharthparmar7 requested changes
Please make the changes. Thank you.

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/components/StageOne/StageOne.js
> +            <Text style={styles.heading1}>Compound interest</Text> is what most
`<Text>` cannot be a child of `<Text>`. Please make the changes.

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/components/StageOne/StageOne.js
> +            <Text style={styles.heading1}>Simple Interest</Text> we are only
same as above.

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/components/StageOne/StageOne.js
> +            focusing on the original principal and the interest rate.{" "}
remove `{" "}`

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/components/StageOne/StageOne.js
> +            With <Text style={styles.heading1}>Compound Interest</Text> we also
<Text> cannot be a child of <Text>. Please make the changes.

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/components/StageOne/StageOne.js
> +            <Text style={styles.heading1}>Simple Interest</Text> and the right
same as above.

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/components/StageOne/StageOne.js
> +            <View style={{ width: "50%" }}>
move your styles to styles.js file.

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/components/StageOne/StageOne.js
> +            <View style={{ width: "50%" }}>
same as above.

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/components/StageOne/styles.js
> +    paddingBottom: 20,
use paddingVertical: 20

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/components/StageOne/styles.js
> +    marginBottom: height * 0.03
use marinVerticle: 20

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/components/StageOne/styles.js
> +    paddingBottom: "2.5%"
use paddingVerticle.

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/components/StageOne/styles.js
> +    paddingBottom: "8%",
use paddingVerticle.

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/screens/Lessons/LessonLibrary.js
> +    console.log(search);
remove this console.log

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/js/screens/Lessons/LessonLibrary.js
> +    console.log(result);
same as above.

2019-06-21 16:17 UTC, siddharthparmar7 commented on client/package.json
> +    "react-native-elements": "^1.1.0",
we do not use react native elements. Please remove this package and use react native components.

2019-06-21 20:48 UTC, siddharthparmar7 requested changes
Move your content to a const or a component state and use it from there instead of hard coding in the text component. Thank you.

2019-06-25 17:10 UTC, siddharthparmar7 approved these changes

2019-06-25 17:10 UTC, merged